{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "e0aaf68e-0f55-4c5d-a152-caeeee261a94",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting auto display for cadquery Workplane and Shape\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "type object 'Face' has no attribute 'makeSplineApprox'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_99/336605287.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m    121\u001b[0m ] for y in range(min_value, max_value, step)]\n\u001b[1;32m    122\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 123\u001b[0;31m \u001b[0msolid\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0msurface\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpoints\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mthickness\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    124\u001b[0m \u001b[0mshow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msolid\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/tmp/ipykernel_99/336605287.py\u001b[0m in \u001b[0;36msurface\u001b[0;34m(points, thickness)\u001b[0m\n\u001b[1;32m    104\u001b[0m     \u001b[0;31m# end def\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    105\u001b[0m     \u001b[0;31m#\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 106\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0mpolyhedron\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0m_all_pts\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0m_all_faces\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    107\u001b[0m \u001b[0;31m# end def\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    108\u001b[0m \u001b[0;31m#\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/tmp/ipykernel_99/336605287.py\u001b[0m in \u001b[0;36m_all_pts\u001b[0;34m()\u001b[0m\n\u001b[1;32m     42\u001b[0m         \u001b[0;31m# makeSplineApprox 的控制點以每行（column）為一組\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     43\u001b[0m         \u001b[0;31m# 因此需要將 points 轉置\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 44\u001b[0;31m         face = Face.makeSplineApprox([[\n\u001b[0m\u001b[1;32m     45\u001b[0m                      \u001b[0mVector\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m*\u001b[0m\u001b[0mpoints\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mri\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0mci\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     46\u001b[0m                 \u001b[0;32mfor\u001b[0m \u001b[0mri\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mrange\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mleng_row\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mAttributeError\u001b[0m: type object 'Face' has no attribute 'makeSplineApprox'"
     ]
    }
   ],
   "source": [
    "# draw-surface\n",
    "# 2021-12-10\n",
    "#\n",
    "import cadquery as cq\n",
    "import pprint\n",
    "from jupyter_cadquery.cadquery import show, PartGroup, Part\n",
    "from jupyter_cadquery import set_defaults, set_sidecar\n",
    "from cadquery import Vector, Vertex, Edge, Wire, Solid, Shell, Face\n",
    "#\n",
    "# Comment/Uncomment  set_defaults() function\n",
    "# if JupyterLab Theme ---> Dark  ; Uncomment it\n",
    "# if JupyterLab Theme ---> Light ; use # make next line being a comment\n",
    "set_defaults(theme=\"dark\") \n",
    "#\n",
    "def polyhedron(points, faces):\n",
    "    def _edges(vectors, face_indices):\n",
    "        leng_vertices = len(face_indices)   \n",
    "        return (Edge.makeLine(vectors[face_indices[i]], \n",
    "                              vectors[face_indices[(i + 1) % leng_vertices]]) \n",
    "                              for i in range(leng_vertices)\n",
    "               )\n",
    "    # end def\n",
    "    vectors = [Vector(*p) for p in points] \n",
    "    return Solid.makeSolid(\n",
    "        Shell.makeShell(Face.makeFromWires(Wire.assembleEdges(_edges(vectors, face_indices)))\n",
    "                        for face_indices in faces)\n",
    "                          )\n",
    "# end def\n",
    "#\n",
    "def surface(points, thickness):\n",
    "    leng_row = len(points)\n",
    "    leng_col = len(points[0])\n",
    "    leng_pts = leng_col * leng_row\n",
    "    \n",
    "    def _all_pts():\n",
    "        half_thickness = thickness / 2\n",
    "        \n",
    "        # 轉為向量    \n",
    "        vectors = [[Vector(*p) for p in row] for row in points]\n",
    "        \n",
    "        # 用於查詢指定位置的法向量\n",
    "        # makeSplineApprox 的控制點以每行（column）為一組\n",
    "        # 因此需要將 points 轉置\n",
    "        face = Face.makeSplineApprox([[\n",
    "                     Vector(*points[ri][ci]) \n",
    "                for ri in range(leng_row)\n",
    "            ] for ci in range(leng_col)]\n",
    "        )\n",
    "        \n",
    "        front_thicken_pts = [] # 正面的點\n",
    "        back_thicken_pts = []  # 背面的點\n",
    "        for row in vectors:\n",
    "            for vt in row:\n",
    "                # 頂點處的單位法向量\n",
    "                n = face.normalAt(vt).normalized()\n",
    "                # 計算正面的點並收集\n",
    "                v = vt + n.multiply(half_thickness)\n",
    "                front_thicken_pts.append([v.x, v.y, v.z])\n",
    "                # 計算背面的點並收集\n",
    "                v = vt + n.multiply(-half_thickness)\n",
    "                back_thicken_pts.append([v.x, v.y, v.z])\n",
    "        return front_thicken_pts + back_thicken_pts\n",
    "    # end def\n",
    "    #\n",
    "    def _all_faces():\n",
    "        # 正面索引\n",
    "        front_faces = []\n",
    "        for ri in range(leng_row - 1):\n",
    "            for ci in range(leng_col - 1):\n",
    "                front_faces.append(\n",
    "                    [ci + leng_col * ri, (ci + 1) + leng_col * ri, (ci + 1) + leng_col * (ri + 1)])\n",
    "                front_faces.append(\n",
    "                    [ci + leng_col * ri, (ci + 1) + leng_col * (ri + 1), ci + leng_col * (ri + 1)])\n",
    "            # end for\n",
    "        # end for\n",
    "        # 背面索引        \n",
    "        back_faces = [[f[2] + leng_pts, f[1] + leng_pts, f[0] + leng_pts] for f in front_faces]      \n",
    "        # 四個邊的索引\n",
    "        side_faces1 = []\n",
    "        for ci in range(leng_col - 1):\n",
    "            side_faces1.append([ci, ci + leng_pts, ci + 1])\n",
    "            side_faces1.append([ci + leng_pts, ci + leng_pts + 1, ci + 1])\n",
    "        # end for    \n",
    "        side_faces2 = []\n",
    "        rx = leng_col - 1\n",
    "        for ri in range(leng_row - 1):\n",
    "            side_faces2.append(\n",
    "                [rx + (ri + 1) * leng_col + leng_pts, rx + (ri + 1) * leng_col, rx + ri * leng_col])\n",
    "            side_faces2.append(\n",
    "                [rx + ri * leng_row + leng_pts, rx + (ri + 1) * leng_col + leng_pts, rx + ri * leng_col])\n",
    "        # end for    \n",
    "        side_faces3 = []\n",
    "        for ci in range(leng_pts - leng_col, leng_pts - 1):\n",
    "            side_faces3.append([ci + 1, ci + leng_pts, ci])\n",
    "            side_faces3.append([ci + 1, ci + leng_pts + 1, ci + leng_pts])\n",
    "        # end for    \n",
    "        side_faces4 = []\n",
    "        for ri in range(leng_row - 1):\n",
    "            side_faces4.append([ri * leng_col, (ri + 1) * leng_col, (ri + 1) * leng_col + leng_pts])\n",
    "            side_faces4.append([ri * leng_col, (ri + 1) * leng_col + leng_pts, ri * leng_row + leng_pts])\n",
    "        # end for\n",
    "        #\n",
    "        return front_faces + back_faces + side_faces1 + side_faces2 + side_faces3 + side_faces4\n",
    "    # end def\n",
    "    #\n",
    "    return polyhedron(_all_pts(), _all_faces())\n",
    "# end def\n",
    "#\n",
    "def paraboloid(x, y):\n",
    "    return [x, y, ((y ** 2) - (x ** 2)) / 4]\n",
    "# end def\n",
    "#\n",
    "min_value = -30\n",
    "max_value = 30\n",
    "step = 5\n",
    "thickness = 0.5\n",
    "\n",
    "points = [[\n",
    "        paraboloid(x / 10, y / 10) \n",
    "    for x in range(min_value, max_value, step)\n",
    "] for y in range(min_value, max_value, step)]\n",
    "\n",
    "solid = surface(points, thickness)\n",
    "show(solid)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f9d293ac-2e09-473f-a23b-12813aac52e6",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
